# Generated by Django 3.2.9 on 2021-11-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.account')),
                ('other_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PolyPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said_by', models.CharField(blank=True, default='Who knows?', max_length=28)),
                ('phrase', models.CharField(max_length=128)),
            ],
        ),
    ]
