# Generated by Django 3.2.24 on 2024-02-26 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import persistence.validators


class Migration(migrations.Migration):

    replaces = [('persistence', '0001_initial'), ('persistence', '0002_character_last_updated')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fork_compatibility', models.CharField(default='Unitystation', help_text='What fork is this character compatible with? This is a simple string, like "Unitystation" or "tg".', max_length=25)),
                ('character_sheet_version', models.CharField(help_text='What character sheet version is this character compatible with? This should be semantically versioned, like "1.0.0" or "0.1.0".', max_length=10, validators=[persistence.validators.validate_semantic_version])),
                ('data', models.JSONField(help_text='Unstructured character data in JSON format.', verbose_name='Character data')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When was this character last updated? Useful for conciliation with the local cache of a character.')),
            ],
        ),
    ]
