version: "3"

x-django-defaults: &django_defaults
  build: .
  env_file: ./.env

services:
  db:
    image: postgres
    env_file: ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web_migration:
    <<: *django_defaults
    command: migrate
    depends_on:
      - db

  web:
    <<: *django_defaults
    depends_on:
      - web_migration
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src

volumes:
  db-data:
