# Generated by Django 3.2.12 on 2022-03-13 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.UUID('387d8683-ef09-4042-b9e5-1b487fb37152'), verbose_name='Verification token'),
        ),
    ]
