# Generated by Django 3.2.12 on 2022-03-13 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.UUID('e617579c-8c17-45f6-9994-f93d8f28cae6'), verbose_name='Verification token'),
        ),
    ]
