# Generated by Django 3.2.22 on 2024-01-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240113_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequestmodel',
            name='token',
            field=models.TextField(),
        ),
    ]
