# Generated by Django 3.2.15 on 2023-10-23 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.UUID('6c74ff29-b92d-4175-8581-e91c38b84195'), verbose_name='Verification token'),
        ),
    ]
