# Generated by Django 3.2.15 on 2023-10-23 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.UUID('32dfaa59-45fc-4c7a-bbd5-b195075e5f89'), verbose_name='Verification token'),
        ),
    ]
