# Generated by Django 3.2.25 on 2025-08-11 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionChallenge',
            fields=[
                ('connection_challenge', models.CharField(help_text="A random challenge string that is independently calculated by both the client and server.\n        Traditionally, this is calculated as SHA-512 of a the Server's public key + a random shared secret generated by the client.", max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_challenge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
