# Generated by Django 3.2.22 on 2024-01-18 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetrequestmodel_expiry_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetrequestmodel',
            name='expiry_datetime',
        ),
        migrations.AddField(
            model_name='passwordresetrequestmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
