# Generated by Django 3.2.22 on 2023-10-23 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.UUID('f4a76c91-a5b1-444e-af33-32c82ac1dc4b'), verbose_name='Verification token'),
        ),
    ]
