name: PR
on:
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        env:
          IMAGE_NAME: unitystation/unitystation_auth
        run: |
          docker pull $IMAGE_NAME
          docker build --pull --cache-from $IMAGE_NAME -t $IMAGE_NAME .
      - name: Test
        env:
          COMPOSE_CMD: docker-compose -f test-compose.yml
        run: |
          $COMPOSE_CMD up -d db
          sleep 5 # let db initialize
          $COMPOSE_CMD run test migrate
          $COMPOSE_CMD run test
