name: Push
on:
  push:
    branches: [main, develop]
    tags: ["*"]

env:
  IMAGE_NAME: unitystation/unitystation_auth

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker pull $IMAGE_NAME
          docker build --pull --cache-from $IMAGE_NAME -t $IMAGE_NAME:latest .

      - name: Log in into Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Add a release tag to image
        if: contains(github.ref, 'refs/tags/')
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:${GITHUB_REF#refs/tags/}

      - name: Push image to registry
        run: |
          docker push $IMAGE_NAME
