name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: plugins
        run: npm install @semantic-release/changelog -D @semantic-release/git -D
      - name: generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    env:
      IMAGE_NAME: unitystation/unitystation_auth
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: lasttag
        uses: WyriHaximus/github-action-get-previous-tag@1.0.0

      # Steps below are copied from main workflow
      - name: Build image
        run: |
          docker pull $IMAGE_NAME
          docker build --pull --cache-from $IMAGE_NAME -t $IMAGE_NAME:latest .

      - name: Log in into Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Add a release tag to image
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:${{ steps.lasttag.outputs.tag }}

      - name: Push image to registry
        run: |
          docker push $IMAGE_NAME
